# Use root/example as user/password credentials
version: '2'
services:
  php:
    container_name: php5
    #image: php:5.6-apache
    build: ./php
    #command: docker-php-ext-install mysql
    volumes:
      - ./www/:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: always
    links:
      - mysql
    ports:
      - 80:80

  mysql:  
   image: mysql:5.5.44
   container_name: mysql
   volumes:
      - ./mysql:/var/lib/mysql
   environment:
    MYSQL_ROOT_PASSWORD: example


  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

